housepower/ClickHouse-Native-JDBC

src/main/java/com/github/housepower/jdbc/data/Block.java

unfortunately, nameWithPosition has wrong index number, therefore getPositionByName/findColumn return wrong position and as result - getString/getInt by column name return SQLException - wrong field == wrong type .

fixed header position by name

---

pom.xml
src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
src/main/java/com/github/housepower/jdbc/ClickHouseResultSet.java
src/main/java/com/github/housepower/jdbc/misc/CheckedIterator.java
src/main/java/com/github/housepower/jdbc/misc/CheckedSupplier.java
src/main/java/com/github/housepower/jdbc/protocol/QueryResponse.java
src/main/java/com/github/housepower/jdbc/statement/ClickHouseStatement.java
src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java

Current solution accumulates all rows in resultset, making it impossible to process large resultsets in streaming fashion.
Change processing such that resultset accumulates a single row.
Is it okay to change language level to Java 8?

Support streaming resultset

---

src/main/java/com/github/housepower/jdbc/NonRegisterDriver.java
src/test/java/com/github/housepower/jdbc/ClickhouseDriverRegisterTest.java
src/test/java/com/github/housepower/jdbc/tool/EmbeddedDriver.java

* avoid creating error connection when multi-drivers were registered
```java
Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
Class.forName("org.apache.phoenix.jdbc.PhoenixDriver");
Connection conn = DriverManager.getConnection("jdbc:phoenix:quorums")
println(conn.getClass() == com.github.housepower.jdbc.ClickHouseConnection.class);
// true
```

Do url check before create connection

---

src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
src/main/java/com/github/housepower/jdbc/statement/ClickHouseStatement.java

Fix exceptions when using flink jdbc.
Flink will call setFetchSize & prepareStatement function when using sink function.
The default implement will cause exception, so i rewrite it with empty implementation to compat flink jdbc sink function.

compat with Flink-JDBC

---

src/main/java/com/github/housepower/jdbc/data/Block.java

Put in a clear error message when validation fails if the column named doesn't exist in the result set.

Clear error message for fetching a column when it doesn't exist

---

src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
src/main/java/com/github/housepower/jdbc/ConnectionState.java
src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedInsertStatement.java
src/test/java/com/github/housepower/jdbc/BatchInsertITest.java

In flink_jdbc , a PreapredInsertStatement will be used more than once.
This pr fix the problem when executeBatch many times.
And I add a state property in ClickhouseConnection,  to ensure the query operation can be execute normally.

fix PrepareInsertStatement Problem

---

pom.xml
src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
src/main/java/com/github/housepower/jdbc/data/type/DataTypeDate.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime64.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDecimal.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeFixedString.java
src/main/java/com/github/housepower/jdbc/serializer/BinaryDeserializer.java
src/main/java/com/github/housepower/jdbc/serializer/BinarySerializer.java
src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java
src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java
src/test/java/com/github/housepower/jdbc/benchmark/ProfileBenchmark.java
src/test/java/com/github/housepower/jdbc/benchmark/Profiler.java
src/test/java/com/github/housepower/jdbc/benchmark/SelectIBenchmark.java

This PR fixes the code of this library, which has some shortcomings:
- uses default charset (breaks serializing Strings from wire protocol)
- uses possibly date formats with incorrect decimal symbols when executed in a locale which uses different decimal symbols (like Hindi/Korean languages)
The detection of problematic parts is done by forbiddenapis (https://github.com/policeman-tools/forbidden-apis), which was included as a new maven plugin. The POM file itsself also had some problems regarding charset encoding (source files were not interpreted as UTF-8); I fixed this, too.
The forbiddenapis plugin found basically those major issues:
1. Wire format encoding/decoding of strings relied on platform's default charset. As soon as you use the JDBC driver on Windows or on other platform that …

Fix problems which makes the JDBC library not platform independent

---

src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedInsertStatement.java
src/test/java/com/github/housepower/jdbc/BatchInsertITest.java

The method executeBatch in ClickHousePreparedInsertStatement should return an array of int. Where each item is 1 indicate that 1 row has been processed successfully instead of -1

fix return value for executeBatch in PreparedInsertStatement

---

src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java
src/main/java/com/github/housepower/jdbc/statement/ClickHouseStatement.java
src/main/java/com/github/housepower/jdbc/wrapper/SQLStatement.java

Remove duplicate interface inheritance as in the following class definition
`public abstract class AbstractPreparedStatement extends ClickHouseStatement implements PreparedStatement `
In the code above: `ClickHouseStatement` extends from `SQLStatement` while `SQLStatement` is already extended from `PreparedStatement`
So `AbstractPreparedStatement` don't need to say that it gonna implements PreparedStatement

Statement inheritance refactoring

---

src/main/java/com/github/housepower/jdbc/settings/ClickHouseConfig.java
src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java

Scenario:
- My ClickHouse server run in Docker with container name: `my_clickhouse_server` ( this is its hostname)
- I have another  microservice A ( run in the same network in Docker) connect to ClickHouse server using ClickHouse JDBC. 
- But i cannot connect to clickhouse using JDBC URL= "jdbc:clickhouse://my_clickhouse_server:9000/mydatabase". throw Connection refused exception.
--> Because this library required hostname must be 1 of 3 types: domain (domain.com, domain.net ... etc), IPv4 , IPv6.

Enhance & Fix parse host name in jdbc connection string

---

clickhouse-native-jdbc-shaded/pom.xml
clickhouse-native-jdbc-shaded/src/main/resources/simplelogger.properties
pom.xml

Add `debug` profile for print log into file `/tmp/clickhouse-native-jdbc.log`.
Build using `mvn clean package -DskipTests -Pdebug`, then get a `clickhouse-native-jdbc-shaded-2.5.0-SNAPSHOT.jar` which will print log into file `/tmp/clickhouse-native-jdbc.log`, it's more useful for debug with `DataGrip` or `DBeaver`.
No impact on normal build process which run without `-Pdebug` option.

(build) debug profile

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeString.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/misc/SQLLexer.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/misc/StringView.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/serde/BinarySerializer.java

Rewrite StringView implements CharSequence

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseSQLException.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ClickHouseSQLExceptionITTest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ClickHouseSQLExceptionITest.java

In some cases, we don't want to introduce an explicit dependency on a concrete clickhouse driver. 
For example, we would use yandex driver for cases where native jdbc driver doesn't support it, but we want to unify the error handling.

Set ErrorCode correctly, so that we can use SQLException without downcast to ClickHouseSQLException

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/data/Block.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSet.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSetMetaData.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedInsertStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/stream/ValuesInputFormat.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/stream/ValuesWithParametersInputFormat.java

It's a correctness issue, and there are minor refactor in addition to bug fix.
There are some `index` start with `1` in JDBC interface definition which constantly confusing us, and I made a change in this PR to clarify that term `index` should always start with `0` in our codebase, and use term `position` to present those stuffs start with `1`.

Fix columnIdx in convertToCkDataType

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/PreparedStatementITest.java

(#314) Fix NPE on clearParameters

---

clickhouse-integration/clickhouse-integration-spark/src/test/scala/com/github/housepower/jdbc/spark/SparkDateITest.scala
clickhouse-integration/clickhouse-integration-spark/src/test/scala/com/github/housepower/jdbc/spark/SparkOnClickHouseITest.scala
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/tool/TestHarness.java

@Guanpx Add a test for #343 and everything works as expected.

[TEST] Add Date test for Spark on ClickHouse

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/data/DataTypeFactory.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/data/type/DataTypeDate32.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedInsertStatement.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/AbstractITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QuerySimpleTypeITest.java

support new datatype Date32
https://clickhouse.com/docs/en/sql-reference/data-types/date32/

add Date32 support

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/buffer/ByteArrayWriter.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/data/Block.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/data/ColumnWriterBuffer.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/data/ColumnWriterBufferFactory.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedInsertStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/serde/BinarySerializer.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/settings/ClickHouseDefines.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/data/ColumnWriterBufferTest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/serde/BinarySerializerTest.java

Implement basic logic of re-using buffers

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/data/type/DataTypeDate.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QuerySimpleTypeITest.java

When date value is bigger than short range, the value will error. because clickhouse date is uint16

fix date value error when bigger than short

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/settings/ClickHouseDefines.java

https://github.com/housepower/ClickHouse-Native-JDBC/pull/382#issuecomment-968740346

Remove final of buffer size in ClickHouseDefines

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/data/type/complex/DataTypeNothing.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QuerySimpleTypeITest.java

Fix Nothing DataType serde

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedInsertStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHouseStatement.java

Return buffers to the pool after executing prepared INSERT statement, so they can be reused again even if statement is not closed

Improve ColumnWriteBuffer recycling

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/buffer/BuffedWriter.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/buffer/ByteArrayWriter.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/buffer/CompressedBuffedWriter.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/buffer/SocketBuffedWriter.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/data/ColumnWriterBuffer.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/serde/BinarySerializer.java

Instead of copying serialized column data from ByteBuffer via intermediate byte[], just write backing array directly. This somewhat couples ColumnWriterBuffer with ByteArrayWriter internals, however as the name implies ByteArrayWriter is expected to use heap buffers (and using direct buffers for block data wouldn't make much sense now anyway - I/O layer is operating on byte[], plus most JVMs impose limits on direct memory allocation).
ByteArrayWriter and CompressedBuffedWriter use fixed-size buffers internally and chunk bytes already.
SocketBuffedWriter may benefit from splitting large writes into smaller ones to minimize malloc/free in native code - but it shouldn't be worse than current situation (at least with compression) and likely to be dubious optimisation.

Further minimize buffer allocation in INSERT path. Remove one of writeBinary() overrides.

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/client/NativeClient.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/settings/SettingKey.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java

Add url parameter `query_id` instead random uuid and it  will affect all statement of same connection

#398 add parameter `query_id`

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/data/Block.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSet.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/stream/ClickHouseQueryResult.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QueryScanStatTest.java

Like `clickhouse-client` return readRows and readBytes.
ReadRow's value equals column`read_rows` of `system.query_log`
ReadBytes value equals column`read_bytes` of `system.query_log`
if `ResultSet` has next value, readRows or readBytes will not exactly the same
Usage
```
((ClickHouseResultSet) rs).getReadRows()
((ClickHouseResultSet) rs).getReadBytes()
```

#400 ClickhouseResultSet add readRows and readBytes

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/client/NativeClient.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickhouseJdbcUrlParser.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/settings/ClickHouseConfig.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/FailoverClickhouseConnectionITest.java

This PR proposes to extend the JDBC URL pattern as follows to support failover.
`jdbc:clickhouse://host1:port1,host2:port2[/database][?prop1=value1&prop2=value2]`
To be clear, do not expect it to act as load balancing, the mechanism of failover is: 
1. try to connect the first host at the beginning
2. if the first host is unreachable, then try the second, and so on
3. when the connection is broken, go 1

Extend JDBC URL pattern to support failover

---

.gitignore
clickhouse-native-jdbc/src/main/java/com/github/housepower/log/Util.java
pom.xml

This PR adds Java 21 support to ClickHouse-Native-JDBC with the following changes:
- ✅ Updated Java version from 11 to 21 in root pom.xml
- ✅ Updated scala-maven-plugin target from jvm-11 to jvm-21
- ✅ Upgraded maven-surefire-plugin and maven-failsafe-plugin to version 3.2.5 for Java 21 compatibility
- ✅ Replaced deprecated SecurityManager with StackWalker API in Util.java
- ✅ Added .trae/ directory to .gitignore
- ✅ All core modules build successfully with Java 21
- ✅ No breaking API changes
- ✅ Backward compatible with existing code
- ✅ Modern Java features ready for future enhancements
- ✅ Project builds and packages successfully
- ✅ Java 21 features verified and working
- ✅ No deprecated API usage detected
This upgrade ensures the project stays current with the latest Java LTS version …

feat: Add Java 21 support and ignore .trae directory
