housepower/ClickHouse-Native-JDBC

README.md
src/main/java/examples/ExecuteQuery.java
src/main/java/examples/SimpleQuery.java

Add readme doc, will be merged after #7

ISSUES-9 add README doc

---

src/main/java/org/houseflys/jdbc/type/ColumnFactory.java
src/main/java/org/houseflys/jdbc/type/column/UUIDColumn.java
src/main/java/org/houseflys/jdbc/type/column/complex/Enum16Column.java
src/main/java/org/houseflys/jdbc/type/column/complex/Enum8Column.java
src/main/java/org/houseflys/jdbc/type/creator/UUIDColumnCreator.java
src/main/java/org/houseflys/jdbc/type/creator/complex/EnumColumnCreator.java
src/test/java/org/houseflys/jdbc/ComplexTypeITest.java
src/test/java/org/houseflys/jdbc/SimpleTypeITest.java

ISSUES-10 Add Enum DataType #10

ISSUES-10 Add Enum8 Enum16  UUID DataType

---

.travis.yml
src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
src/main/java/com/github/housepower/jdbc/connect/PhysicalConnection.java
src/main/java/com/github/housepower/jdbc/data/Block.java
src/main/java/com/github/housepower/jdbc/data/DataTypeFactory.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeArray.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeEnum16.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeEnum8.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeFixedString.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeNullable.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeTuple.java
src/main/java/com/github/housepower/jdbc/protocol/DataResponse.java
src/main/java/com/github/housepower/jdbc/protocol/ExtremesResponse.java
src/main/java/com/github/housepower/jdbc/protocol/RequestOrResponse.java
src/main/java/com/github/housepower/jdbc/protocol/TotalsResponse.java
src/test/java/com/github/housepower/jdbc/AbstractITest.java
src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java
src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java
src/test/java/com/github/housepower/jdbc/InsertSimpleTypeITest.java
src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java

ISSUES-15 add travis

---

pom.xml
src/main/java/com/github/housepower/jdbc/data/DataTypeFactory.java
src/main/java/com/github/housepower/jdbc/data/type/DataTypeDate.java
src/test/java/com/github/housepower/jdbc/PreparedStatementITest.java

ISSUES-19 add release plugin

---

README.md

ISSUES-19 fixed document

---

src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java

ISSUES-32 fix hostname not found bug

---

README.md
pom.xml
src/main/java/com/github/housepower/jdbc/data/type/DataTypeDate.java
src/test/java/com/github/housepower/jdbc/PreparedStatementITest.java

[RELEASE] v.1.1-testing

---

src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
src/main/java/com/github/housepower/jdbc/settings/ClickHouseConfig.java
src/main/java/com/github/housepower/jdbc/wrapper/SQLConnection.java

ISSUES-46 add isValid for connection

---

src/main/java/com/github/housepower/jdbc/stream/ValuesInputFormat.java
src/test/java/com/github/housepower/jdbc/InsertSimpleTypeITest.java

ISSUES-59 fix multiple values insert query with comma

---

src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt16.java
src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt32.java
src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt64.java
src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt8.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeArray.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeNullable.java
src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java
src/test/java/com/github/housepower/jdbc/InsertSimpleTypeITest.java
src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java
src/test/java/com/github/housepower/jdbc/QuerySimpleTypeITest.java

Access rules:
UInt8 -> getShort
UInt16 -> getInt
UInt32 -> getLong
UInt64 -> getBigDecimal

Support UInt8,UInt16,UIn32,UInt64 types

---

src/main/java/com/github/housepower/jdbc/ClickHouseArray.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeArray.java
src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java

dataTypeArray support array flatten  deserializeBinaryBulkWithMultipleStreams

---

src/main/java/com/github/housepower/jdbc/data/DataTypeFactory.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDecimal.java
src/test/java/com/github/housepower/jdbc/DecimalTypeTest.java

Add support for decimal data type.
Decimal128 is unsupported.

Add decimal  support

---

pom.xml

support assembly compile, it can packages a dependencies jar ball
```
mvn clean package assembly:single -DskipTests
[INFO] Scanning for projects...
[INFO]
[INFO] ------------< com.github.housepower:clickhouse-native-jdbc >------------
[INFO] Building clickhouse-native-jdbc 1.8-stable-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ clickhouse-native-jdbc ---
[INFO] Deleting /Users/wgzhao/Codes/ClickHouse-Native-JDBC/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ clickhouse-native-jdbc ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO]
[INFO] --- …
```

support assmebly plugin

---

.travis.yml
src/main/java/com/github/housepower/jdbc/data/type/DataTypeDate.java
src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java
src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java

 fix date timezone

---

src/main/java/com/github/housepower/jdbc/data/Block.java

This helps in debugging any mismatch in the type of expected values and provided values.

catch class cast exception and error log relevant info

---

src/main/java/com/github/housepower/jdbc/data/DataTypeFactory.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime64.java
src/main/java/com/github/housepower/jdbc/misc/SQLLexer.java
src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java

Hi, guys!
I want to use this awesomeness feature of clickHouse, it is very helpful format for time series data.  
I've used DataTypeDateTime as example

datetime64 supported

---

src/main/java/com/github/housepower/jdbc/data/Block.java
src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedInsertStatement.java
src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedQueryStatement.java
src/main/java/examples/BatchQuery.java

added method to get set object for a column in the block, added toString methods in prepared statements to provide SQL query if needed in debugging

method to print prepared statement query

---

.gitignore
src/main/java/com/github/housepower/jdbc/data/DataTypeFactory.java
src/main/java/com/github/housepower/jdbc/data/type/DataTypeIPv4.java
src/test/java/com/github/housepower/jdbc/InsertSimpleTypeITest.java

Add ipv4 insert

---

src/main/java/com/github/housepower/jdbc/data/Column.java
src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeNullable.java
src/test/java/com/github/housepower/jdbc/BatchInsertITest.java
src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java

Refactor nullable deserializeBinary and serializeBinary

---

src/main/java/com/github/housepower/jdbc/settings/ClickHouseConfig.java
src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java

fix connection timeout unit

---

src/main/java/com/github/housepower/jdbc/ClickHouseResultSet.java
src/test/java/com/github/housepower/jdbc/BatchInsertITest.java
src/test/java/com/github/housepower/jdbc/PreparedStatementITest.java
src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java

nullable returns null instead of default value

---

.github/workflows/test.yml
.travis.yml
src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
src/main/java/com/github/housepower/jdbc/settings/ClickHouseConfig.java
src/main/java/com/github/housepower/jdbc/statement/ClickHouseStatement.java
src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java

refactor exceptions in ClickHouseStatement

---

src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java

Hello,
This is to complete JDBC compliance and avoid some SQLFeatureNotSupportedException with old JDBC frameworks.

complete JDBC compliance

---

src/main/java/com/github/housepower/jdbc/misc/SQLLexer.java
src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java
src/test/java/com/github/housepower/jdbc/QuerySimpleTypeITest.java
src/test/java/com/github/housepower/jdbc/SQLLexerITest.java

- fix: numberLiteral in SQLLexer and add tests
- fix: error to query with single quoted string param in ClickHousePreparedQueryStatement

fix numberLiteral in sqllexer and query with single quoted string param in ClickHousePreparedQueryStatement

---

src/test/java/com/github/housepower/jdbc/IssueReproduceITest.java

add tests for issues #63

---

clickhouse-native-jdbc/pom.xml
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeDate.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime64.java
pom.xml

(#159) remove joda-time

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSetMetaData.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/IDataType.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeDate.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeFloat32.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeFloat64.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeIPv4.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt16.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt32.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt64.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt8.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeString.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeUUID.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeArray.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime64.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDecimal.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeEnum16.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeEnum8.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeFixedString.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeNullable.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeTuple.java

support getPrecision && getScale

---

README.md
clickhouse-native-jdbc/pom.xml
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/BatchInsertITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/DecimalTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertSimpleTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/PreparedStatementITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QueryRandomITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QuerySimpleTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ResultSetMetadataITest.java
pom.xml

- move some maven plugins to parent pom.xml
- remove jdk-deprecated reference
- extract maven properties `deploy.repo.snapshots`, `deploy.repo.release` (for deploy private nexus)
All deprecated warnings are caused by referencing java legacy `Date` system API. I open an issue #164  to discuss migrate to `java.time`.

Improve Code and Maven conf

---

clickhouse-native-jdbc/pom.xml
pom.xml

Migrate to org.lz4:lz4-java

---

clickhouse-native-jdbc/pom.xml
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/buffer/SocketBuffedReaderTest.java
pom.xml

- migrate to mockito 3
- bump mockito 3.6.0
close #175

Migrate to mockito 3

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/buffer/ByteArrayWriter.java
examples/src/main/java/examples/BatchQuery.java

https://lgtm.com/projects/g/housepower/ClickHouse-Native-JDBC/alerts/?mode=list

Fix LGTM alerts

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeFloat64.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt16.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt32.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt64.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt8.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeUUID.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeEnum16.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeEnum8.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeNullable.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/misc/ClickHouseCityHash.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/misc/DateTimeHelper.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/misc/Slice.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedQueryStatement.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/benchmark/AbstractInsertIBenchmark.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/benchmark/Main.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/benchmark/ProfileBenchmark.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/benchmark/Profiler.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/benchmark/RowBinaryStringIBenchmark.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/benchmark/WideColumnDoubleInsertIBenchmark.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/benchmark/WideColumnIntInsertIBenchmark.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/benchmark/WideColumnStringInsertIBenchmark.java
dev/checkstyle-suppression.xml
dev/checkstyle.xml
dev/license.header
pom.xml

(#172) enable checkstyle

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/settings/ClickHouseConfig.java

About box&unbox type:
I know some best practice say, if you use Generic Type, you should use boxed type to avoid box&unbox overhead. But in performance insensitive case, I prefer Kotlin Principle, use `int` to represent a NotNull value, and `Integer` to represent a `Nullable` value.

Fix potential concurrence issue

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSet.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/Block.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/Column.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/ColumnArray.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/ColumnFactory.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/ColumnNullable.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/ColumnTuple.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/IColumn.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/IDataType.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeArray.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeNullable.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeTuple.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/BatchInsertITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java
docs/Process.md

Refactor insert2

---

clickhouse-integration/clickhouse-integration-spark/src/test/scala/com.github.housepower.jdbc.spark/SparkOnClickHouseITest.scala
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/Block.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/ColumnNullable.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeDate.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt64.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/protocol/HelloResponse.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedInsertStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedQueryStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHouseStatement.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/AbstractITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/PreparedStatementITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java

Fix timezone issue

---

.github/workflows/build.yml
.github/workflows/integration-test.yml
README.md
clickhouse-native-jdbc/pom.xml
pom.xml

Integrate with codecov

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/stream/ValuesWithParametersInputFormat.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertSimpleTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/PreparedStatementITest.java

Support Boolean in pstmt

---

.github/workflows/integration-test.yml
clickhouse-integration/clickhouse-integration-spark/pom.xml
docs/Release.md
pom.xml

Invalid package clickhouse-integration-spark_2.12

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/settings/ClickHouseConfig.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ClickHouseConnectionITest.java

Implement Jdbc catalog schema and fix ClickHouseConfig build

---

clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/AbstractITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/PreparedStatementITest.java
examples/pom.xml
examples/src/main/resources/simplelogger.properties
examples/src/test/java/examples/DataSourceITest.java
examples/src/test/java/examples/Dbcp2ITest.java
examples/src/test/java/examples/DruidITest.java
examples/src/test/java/examples/HikariCpITest.java
pom.xml

Integration tests with connection pool

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSet.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/DataTypeFactory.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeString.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeFixedString.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/serializer/BinaryDeserializer.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/serializer/BinarySerializer.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/settings/ClickHouseConfig.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/settings/SettingKey.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHouseStatement.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/AbstractITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertSimpleTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/IssueReproduceITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/PreparedStatementITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QueryRandomITest.java

add characterEncoding parameter suppprt && add setBytes getBytes

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/Block.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/Column.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/ColumnArray.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/ColumnNullable.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/ColumnTuple.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/protocol/DataRequest.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/protocol/DataResponse.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/protocol/ExceptionResponse.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/protocol/ExtremesResponse.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/protocol/HelloRequest.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/protocol/HelloResponse.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/protocol/QueryRequest.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/protocol/TotalsResponse.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/serializer/BinaryDeserializer.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/serializer/BinarySerializer.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/settings/ISettingType.java

rename {write|read}StringBinary => {write|read}UTF8StringBinary

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime64.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java

Fix DateTime64 nanos and scale

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/annotation/Issue.java

Reset connection STATE when recreate connection

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/connect/PhysicalConnection.java
clickhouse-native-jdbc/src/test/resources/simplelogger.properties

followup #221 
close #181 #222 
May be related to #100

Skip remaining response when consume PingResponse

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/DataTypeFactory.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/IDataType.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeDate.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeFloat32.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeFloat64.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeIPv4.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt16.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt32.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt64.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeInt8.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/DataTypeUUID.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeArray.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeCreator.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime64.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDecimal.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeEnum16.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeEnum8.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeFixedString.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeNullable.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeString.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeTuple.java

add alias types support

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/ColumnWriterBuffer.java

Explicit upcast ByteBuffer to Buffer

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/BalancedClickhouseDataSource.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseArray.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseDatabaseMetadata.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSet.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseStruct.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/buffer/SocketBuffedWriter.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/connect/NativeClient.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDateTime64.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/misc/DateTimeUtil.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/misc/Either.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/serde/BinaryDeserializer.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/serde/BinarySerializer.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/settings/SettingKey.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHouseStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/wrapper/SQLConnection.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/wrapper/SQLDatabaseMetadata.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/wrapper/SQLResultSet.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/wrapper/SQLResultSetMetaData.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/wrapper/SQLStatement.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/wrapper/SQLWrapper.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ClickHouseDatabaseMetadataITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/PreparedStatementITest.java

Refactor and fixup

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSet.java

Enhance null check on ClickHouseResultSet#getXXX

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/DataTypeFactory.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeNothing.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java

#260 Handle Nothing datatype

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseDriver.java

ClickHouseConnection#connect should return null for unaccepted url

---

clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/AbstractITest.java

Added user & password for ClickHouse unit tests
Close #262

#262 Added user & password for ClickHouse unit tests

---

clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/AbstractITest.java

#276 Added database for tests

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/data/type/complex/DataTypeDecimal.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/misc/BytesUtil.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/DecimalTypeITest.java

Fix Negative Decimal deser bug

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSetMetaData.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ClickHouseResultSetMetaDataITest.java

(bugfix) Fix ResultSetMetaData.isSigned

---

README.md
README_zh.md

This PR raised from my forked repo, hope the solution mentioned in #292 works, and close #292.

(docs) minor change

---

.github/workflows/benchmark.yml
.github/workflows/integration-test.yml
clickhouse-integration/clickhouse-integration-spark/pom.xml
clickhouse-native-jdbc/pom.xml
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHousePreparedInsertStatement.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/AbstractITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/BalancedClickhouseDataSourceITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/BalancedClickhouseDataSourceTest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ClickHouseDatabaseMetadataITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/benchmark/AbstractIBenchmark.java
clickhouse-native-jdbc/src/test/resources/simplelogger.properties
docker-compose.yml
examples/pom.xml
pom.xml

Migrate to Testcontainers

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/client/NativeClient.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/client/NativeContext.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/BalancedClickhouseDataSource.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseDriver.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickhouseJdbcUrlParser.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/protocol/QueryRequest.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/serde/SettingType.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/settings/ClickHouseConfig.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/settings/SettingKey.java

When use distribute engine, i.e. Spark, we need serde transport cfg between nodes.

Make ClickHouseConfig Serializable

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseDatabaseMetadata.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ClickHouseDatabaseMetadataITest.java

[#336] Correct ClickHouseDatabaseMetadata#supportsBatchUpdates

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java

[branch-2.5] Support setDate with Calendar in pstmt

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/AbstractPreparedStatement.java

Support setDate with Calendar in pstmt

---

pom.xml

Bump aircompressor 0.21

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/client/NativeClient.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickhouseJdbcUrlParser.java
clickhouse-native-jdbc/src/main/java/com/github/housepower/settings/ClickHouseConfig.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/ConnectionParamITest.java
clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/FailoverClickhouseConnectionITest.java

* support failover
* fix pattern and add ut
* fix ut wrong pair host and port

Extend JDBC URL pattern to support failover (#411)

---

clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseConnection.java

fixbug/#432: The insert exception also sets the state to idle
